version: "3.9"

# Serviços
services:
  database:
    image: postgres:14.5-alpine
    build:
      context: .
      dockerfile: ./Dockerfile_db
    container_name: db
    restart: always
    user: postgres  # importante definir o usuário
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - LC_ALL=C.UTF-8
      - POSTGRES_PASSWORD=postgres  # senha padrão
      - POSTGRES_USER=postgres  # usuário padrão
      - POSTGRES_DB=db  # necessário porque foi configurado assim no settings
    ports:
      - "5434:5432"  # repare na porta externa 5434
    networks:
      - postgres

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: unless-stopped
    volumes:
      - pgadmin:/var/lib/pgadmin
      - ./server.json:/pgadmin4/servers.json
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - 5050:80
    networks:
      - postgres

  nork:
      container_name: nork
      build:
        context: .
        dockerfile: ./Dockerfile
      ports:
        - 8080:8080
      volumes:
        - ./nork:/nork
      environment:
        - FLASK_APP=main.py
        - DB_HOST=localhost
        - POSTGRES_DB=db
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
      depends_on:
        - database

networks:
  postgres:

volumes:
  pgdata:  # mesmo nome do volume externo definido na linha 10
  pgadmin:
